//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ChildResponse defines model for ChildResponse.
type ChildResponse struct {
	BirthMonth *int                `json:"birth_month,omitempty"`
	BirthYear  *int                `json:"birth_year,omitempty"`
	ClerkOrgId *string             `json:"clerk_org_id,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Nickname   *string             `json:"nickname,omitempty"`
}

// CreateChildRequest defines model for CreateChildRequest.
type CreateChildRequest struct {
	BirthMonth int `json:"birth_month"`
	BirthYear  int `json:"birth_year"`
	Consent    struct {
		AppVersion         string `json:"app_version"`
		ConsentTextVersion string `json:"consent_text_version"`
	} `json:"consent"`
	Nickname string `json:"nickname"`
}

// ErasureConfirmation defines model for ErasureConfirmation.
type ErasureConfirmation struct {
	DeletedChildren                *int    `json:"deleted_children,omitempty"`
	DeletedConsentEvents           *int    `json:"deleted_consent_events,omitempty"`
	DeletedDeviceTokens            *int    `json:"deleted_device_tokens,omitempty"`
	DeletedEvents                  *int    `json:"deleted_events,omitempty"`
	DeletedNotificationPreferences *int    `json:"deleted_notification_preferences,omitempty"`
	RequestedAt                    *string `json:"requested_at,omitempty"`
	RequestedBy                    *string `json:"requested_by,omitempty"`
}

// ProblemDetail defines model for ProblemDetail.
type ProblemDetail struct {
	Detail *string `json:"detail,omitempty"`
	Status *int    `json:"status,omitempty"`
	Title  *string `json:"title,omitempty"`
	Type   *string `json:"type,omitempty"`
}

// PostV1ChildrenJSONRequestBody defines body for PostV1Children for application/json ContentType.
type PostV1ChildrenJSONRequestBody = CreateChildRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Delete the entire account and all associated data (GDPR/COPPA erasure)
	// (DELETE /v1/account)
	DeleteV1Account(w http.ResponseWriter, r *http.Request)
	// List the caller's active-org children
	// (GET /v1/children)
	GetV1Children(w http.ResponseWriter, r *http.Request)
	// Create a child profile with parental consent (atomic consent gate)
	// (POST /v1/children)
	PostV1Children(w http.ResponseWriter, r *http.Request)
	// Delete a child profile and all associated data (GDPR/COPPA erasure)
	// (DELETE /v1/children/{id})
	DeleteV1ChildrenId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteV1Account operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1Account(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteV1Account(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV1Children operation middleware
func (siw *ServerInterfaceWrapper) GetV1Children(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1Children(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1Children operation middleware
func (siw *ServerInterfaceWrapper) PostV1Children(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1Children(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteV1ChildrenId operation middleware
func (siw *ServerInterfaceWrapper) DeleteV1ChildrenId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteV1ChildrenId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/account", wrapper.DeleteV1Account)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/children", wrapper.GetV1Children)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/children", wrapper.PostV1Children)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/children/{id}", wrapper.DeleteV1ChildrenId)

	return m
}
